// Registry of every form the portal accepts. Key matches the frontend formKey.
// - `table`:    MySQL table name
// - `fields`:   scalar columns (strings, numbers, dates). Frontend sends these as text fields.
// - `json`:     columns that hold JSON-encoded values (grids, arrays).
// - `booleans`: fields that should be coerced to 0/1 for TINYINT storage.
// - `files`:    multer field name(s). Single file OR array of files per field.
//               { field: 'attachment', multiple: false, column: 'attachment' }
//               The column receives a JSON blob of file metadata.

export const FORMS = {
  'cash-received-arden': {
    table: 'cash_received_arden',
    fields: [
      'date',
      'opening_cash',
      'total_cash_received',
      'total_check_received',
      'total',
      'closing_balance',
      'ext_no',
      'remarks',
    ],
  },
  'cash-received-wvl': {
    table: 'cash_received_wvl',
    fields: [
      'date',
      'opening_cash',
      'total_cash_received',
      'total_check_received',
      'total',
      'closing_balance',
      'ext_no',
      'remarks',
    ],
  },
  'managers-opening-checklist-arden': {
    table: 'managers_opening_checklist_arden',
    fields: [
      'date',
      'name',
      'comments',
      'ext_no',
      'prepared_for_sales_meeting',
      'prepared_for_sales_meeting_describe',
      'all_team_members_arrived',
      'asked_for_quote_sheet',
      'assigned_work',
      'assigned_work_describe',
    ],
    json: ['checklist', 'checklist_names'],
    files: [
      {
        field: 'open_sign_on_image',
        column: 'open_sign_on_image',
        multiple: false,
        filenamePrefix: 'OpenSignOn',
      },
    ],
  },
  'managers-opening-checklist-waynesville': {
    table: 'managers_opening_checklist_waynesville',
    fields: [
      'date',
      'name',
      'comments',
      'ext_no',
      'prepared_for_sales_meeting',
      'prepared_for_sales_meeting_describe',
      'all_team_members_arrived',
      'asked_for_quote_sheet',
      'assigned_work',
      'assigned_work_describe',
    ],
    json: ['checklist', 'checklist_names'],
    files: [
      {
        field: 'open_sign_on_image',
        column: 'open_sign_on_image',
        multiple: false,
        filenamePrefix: 'OpenSignOn',
      },
    ],
  },
  'managers-closing-checklist-arden': {
    table: 'managers_closing_checklist_arden',
    fields: [
      'date',
      'name',
      'scanned_checks_to_bank',
      'sent_report_to_team_india',
      'comment',
      'talking_points',
      'ext_no',
      'birdeye_reviews_requested',
    ],
    json: ['checklist'],
    files: [
      {
        field: 'dt_no_pickups_screenshot',
        column: 'dt_no_pickups_screenshot',
        multiple: false,
        filenamePrefix: 'DispatchScreenshot',
      },
    ],
  },
  'managers-closing-checklist-waynesville': {
    table: 'managers_closing_checklist_waynesville',
    fields: [
      'date',
      'name',
      'scanned_checks_to_bank',
      'sent_report_to_team_india',
      'comment',
      'talking_points',
      'ext_no',
      'birdeye_reviews_requested',
    ],
    json: ['checklist'],
    files: [
      {
        field: 'dt_no_pickups_screenshot',
        column: 'dt_no_pickups_screenshot',
        multiple: false,
        filenamePrefix: 'DispatchScreenshot',
      },
    ],
  },
  'warehouse-notification': {
    table: 'warehouse_notification',
    fields: [
      'date',
      'originator',
      'customer_name',
      'sale_no',
      'status',
      'assembly_required',
      'assembly_remark',
      'comment',
    ],
  },
  'warehouse-opening-checklist': {
    table: 'warehouse_opening_checklist',
    fields: [
      'date',
      'person',
      'pieces_in_route',
      'stops_in_route',
      'trucks_scheduled',
      'manifest_checked',
      'manifest_report_issues',
      'manifest_issue_details',
      'cods_confirmed',
      'cods_file_no',
      'dt_rv_match',
      'dt_rv_explain',
      'dt_notifications',
      'prev_day_finished',
      'return_items_report',
      'return_items_count',
      'email_voice_mail',
      'email_voice_mail_count',
      'email_voice_mail_explain',
      'today_items_confirmed',
      'today_items_count',
      'next_day_confirmed',
      'team_wearing_uniform',
      'truck_loading_monitored',
      'truck_loading_explain',
      'ext_no',
    ],
    files: [
      {
        field: 'prev_day_screenshot',
        column: 'prev_day_screenshot',
        multiple: false,
        filenamePrefix: 'PrevDayRoute',
      },
      {
        field: 'uniform_photo',
        column: 'uniform_photo',
        multiple: false,
        filenamePrefix: 'CFCUniform',
      },
      {
        field: 'truck_loading_photo',
        column: 'truck_loading_photo',
        multiple: false,
        filenamePrefix: 'TruckLoading',
      },
    ],
  },
  'warehouse-closing-checklist': {
    table: 'warehouse_closing_checklist',
    fields: [
      'date',
      'name',
      'trucks_received',
      'paperwork_completed',
      'pieces_in_route',
      'stops_in_route',
      'trucks_scheduled',
      'next_day_delivery',
      'arden_pickup',
      'waynesville_pickup',
      'line_up_comments',
      'dispatch_track_comments',
      'comments',
      'time_clocked_out',
    ],
    json: ['line_up', 'dispatch_track', 'electronic_devices', 'warehouse'],
  },
  'part-received': {
    table: 'part_received',
    fields: [
      'date',
      'your_name',
      'shipping_company',
      'vendor',
      'comment',
    ],
    booleans: ['part_received', 'need_po'],
    files: [{ field: 'files', multiple: true, column: 'files' }],
  },
  'delivery-checklist': {
    table: 'delivery_checklist',
    fields: [
      'sale_number',
      'pwr_check',
      'clean_check',
      'functionality',
      'damage',
      'all_parts',
      'pwr_supply',
      'stains',
      'all_items_loaded',
      'checked_by',
      'ready_for_delivery',
      'remarks',
      'damage_customer_name',
      'damage_sales_number',
    ],
    files: [
      { field: 'attachment', multiple: false, column: 'attachment' },
      {
        field: 'damage_photo',
        column: 'damage_photo',
        multiple: false,
        filenamePrefix: 'DamagePhoto',
      },
      {
        field: 'loading_area_photo',
        column: 'loading_area_photo',
        multiple: false,
        filenamePrefix: 'LoadingArea',
      },
      {
        field: 'all_parts_photo',
        column: 'all_parts_photo',
        multiple: false,
        filenamePrefix: 'AllParts',
      },
    ],
  },
  'pre-delivery-checklist': {
    table: 'pre_delivery_checklist',
    fields: [
      'date',
      'items_ready',
      'items_ready_exceptions',
      'clean_exceptions',
      'accessories_available',
      'if_no_explain',
      'accessories_exceptions',
      'damages',
      'delivery_manager',
      'warehouse_manager',
      'power_supply_on_item',
      'power_supply_status',
      'bed_on_truck',
      'rails_slats_checked',
    ],
    json: ['clean_status'],
    files: [
      { field: 'exception_pics', multiple: true, column: 'exception_pics' },
      {
        field: 'rails_slats_image',
        column: 'rails_slats_image',
        multiple: false,
        filenamePrefix: 'RailsSlats',
      },
    ],
  },
  'to-do-list': {
    table: 'to_do_list',
    fields: ['your_name', 'task', 'ext_no', 'remarks'],
    files: [{ field: 'attachment', multiple: false, column: 'attachment' }],
  },
  'hot-button-status-call-alert': {
    table: 'hot_button_status_call_alert',
    fields: [
      'sales_person_name',
      'concern_type',
      'store',
      'customer_name',
      'sale_number',
      'sale_date',
      'description',
      'steps_taken',
    ],
  },
  'customer-service-request': {
    table: 'customer_service_request',
    fields: [
      'date',
      'your_name',
      'notice_type',
      'customer_name',
      'phone',
      'item_id',
      'bar_code',
      'location',
      'description_of_problem',
      'note',
    ],
    files: [
      {
        field: 'damage_image',
        column: 'damage_image',
        multiple: true,
        filenamePrefix: 'DamageOnFloor',
      },
    ],
  },
}
